version: '3'
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:80" # Maps host 8080 to container port 80
    networks:
      - app_network

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
